[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = {path = "../"}
minifb = "0.23"
ttf-parser = "0.15"
roxmltree = "0.14"
svgtypes = "0.8"

[profile.release]
debug = true
