[workspace]

members = [
    "spall-rs",
    "rug",
    "examples/vg-inputs",
    "examples/raw",
    "examples/api",
    "examples/png",
]

default-members = ["examples/png"]


[profile.release]
debug = true

